@startuml
!include style.puml
skinparam {
arrowThickness 1.1
arrowColor MODEL_COLOR_T1
classBackgroundColor MODEL_COLOR_T1
classBackgroundColor<<HiddenOutside>> #FFFFFF
classBorderColor<<HiddenOutside>> #FFFFFF
classFontColor<<HiddenOutside>> #FFFFFF
classStereotypeFontColor<<HiddenOutside>> #FFFFFF
}

Class hideOutside <<HiddenOutside>>

Package Model <<Rectangle>>{
Interface ObservableList <<Interface>>
Interface Models <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface ReadOnlyXYZBook <<Interface>>
Interface Model <<Interface>>
Class ModelManagers
Class UserPrefs
Class UniqueXYZList
Class XYZModelManager
Class ItemComparator
Class XYZBook
Interface XYZModel <<Interface>>
Class XYZ
note right of XYZ
    XYZ = Item, Delivery
    UniqueXYZList = UniqueItemList, UniqueDelivery List
    XYZBook = ItemBook, DeliveryBook
end note
}

hideOutside ..> Models
ModelManagers .U.|> Models
ModelManagers o-L-> "2" XYZModel
XYZModel o-L-> "0..1" ItemComparator
XYZModel .U.|> Model
XYZModel .U.|> ObservableList
XYZModelManager .U.|> XYZModel
XYZModelManager o--> UserPrefs
XYZModelManager o--> "1" XYZ
XYZModelManager o--> XYZBook
XYZBook "1..20" o-D-> "1" UniqueXYZList
XYZBook .U.|> ReadOnlyXYZBook
UniqueXYZList o--> "*" XYZ
UserPrefs .U.|> ReadOnlyUserPrefs


@enduml
